### ISSUE TITLE
The link of visual and text features cannot be opened

### ISSUE THREAD

**Issue by ppengzeng** [tgc1997/RMN#1]
Please provide a valid link. Thanks

**Comment by daqingliu** [comment]
We have tested the links and they are accessible both in China mainland and abroad. Could you please provide more information about your network config?

**Comment by jun0wanan** [comment]
Because we are not your school student , we have no id to download ....   So maybe you can give me another link? maybe google

**Comment by jun0wanan** [comment]
> We have tested the links and they are accessible both in China mainland and abroad. Could you please provide more information about your network config?

we also can not apply for an account in your link .. 😭  If you have time ,please give us a link . Thank you !!! (●'◡'●)

**Comment by daqingliu** [comment]
Please follow the steps:
1. Enter the folder
2. Choose all files
3. Download

Let me know whether it works or not

**Comment by jun0wanan** [comment]
> 请按照以下步骤操作：
> 
> 1. 输入资料夹
> 2. 选择所有文件
> 3. 下载
> 
> 让我知道它是否有效

ok, it can download . Thank you!!!

**Comment by ydwl-lynn** [comment]
thanks，It is useful。
