### ISSUE TITLE
Spatial Feats

### ISSUE THREAD

**Issue by arnavc1712** [tgc1997/RMN#19]
Hi,
I see you using the 2D CNN features (1536 dim), 3D CNN features (1024 dim), RCNN features (2048 dim). I also see something called spatial features of 5 dimensions. What are these features? I could not find them mentioned anywhere in the paper?

**Comment by tgc1997** [comment]
Hi, we use the position (4 dims) and the area (1 dim) of the region as spatial feature

At2021-07-26 17:08:52，Arnav ***@***.***:

Hi,
I see you using the 2D CNN features (1536 dim), 3D CNN features (1024 dim), RCNN features (2048 dim). I also see something called spatial features of 5 dimensions. What are these features? I could not find them mentioned anywhere in the paper?

**Comment by arnavc1712** [comment]
Hi @tgc1997 ,
Thanks for the revert. What kind of normalization do you use for scaling the box coordinates?

**Comment by arnavc1712** [comment]
@tgc1997,
Thank you!

**Comment by tgc1997** [comment]
we use the following code for normalization:
```python
def _boxes2sfeat(boxes, im):
    S_H = im.shape[0]
    S_W = im.shape[1]
    S_A = S_W * S_H

    boxes = np.asarray(boxes)
    # calculate sfeat
    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]
    Sa = (x2 - x1) * (y2 - y1)
    sfeat = np.hstack(((x1/S_W)[:, np.newaxis],
                       (y1/S_H)[:, np.newaxis],
                       (x2/S_W)[:, np.newaxis],
                       (y2/S_H)[:, np.newaxis],
                       (Sa/S_A)[:, np.newaxis]))
    return sfeat
```
