### ISSUE TITLE
Exception: Model not supported: RMN

### ISSUE THREAD

**Issue by ydwl-lynn** [tgc1997/RMN#8]
when I run train.py,the following error appears：
![12](https://user-images.githubusercontent.com/56346294/96448372-dde8d880-1245-11eb-83e6-f4e6675c4806.png)

**Comment by tgc1997** [comment]
Please install allennlp by running $pip install allennlp, and let me know if this works or not

**Comment by ydwl-lynn** [comment]
The problem is solved.Thanks!

**Comment by ydwl-lynn** [comment]
when I install allennlp, I run train.py only could use CPU.Do you know why?

**Comment by tgc1997** [comment]
could you give more information  about your error

**Comment by jeripothula-prudviraj** [comment]
@tgc1997 getting syntax error while evaluating the model 
![Selection_069](https://user-images.githubusercontent.com/25901437/102215489-cb1a1980-3eff-11eb-9008-820f55e0f378.png)
